Removendo menu da landing page
OsProgramadores/portalestagio pull request #48
Opened 2024-02-26 00:11 UTC by Zezola

Removendo o menu da landing page. Menu continua presente na pagina de cadastro e busca de vagas.

2024-02-26 00:20 UTC, magnussolidus commented on app/page.tsx
> +
Linha em branco extra, remova se possível.

2024-02-26 00:20 UTC, magnussolidus commented on app/ui/layout.tsx
> -      <div className="w-full flex-none md:w-20">
O que essa remoção faz?

2024-02-26 00:20 UTC, magnussolidus commented on app/cadastro/page.tsx
> +      <BuscaLayout>
Se você extraiu o layout para um arquivo próprio, ainda é necessário o código dentro da tag `BuscaLayout`?

2024-02-26 00:25 UTC, Zezola commented on app/ui/layout.tsx
> -      <div className="w-full flex-none md:w-20">
Retira o elemento do menu, que no caso era a <TopNav /> desse layout. 
Pelo que entendi, esse é o layout que vamos puxar para a nossa landing page. Mas como ela não vai precisar de menu, deixei o menu em um arquivo de layout separado: 
/app/busca/layout.tsx

2024-02-26 00:29 UTC, Zezola commented on app/cadastro/page.tsx
> +      <BuscaLayout>
Creio que sim, pois quando testei não colocar dentro da tag, o menu não apareceu. Imagino que seja porque o layout que estamos puxando está em outro diretório, se observar no diretório busca conseguimos renderizar o menu normalmente sem utilizar a tag. Pelo que entendi na documentação quando queremos referenciar um layout que está em outro diretório vamos precisar da tag

2024-02-26 00:59 UTC, magnussolidus approved these changes
LGTM.

2024-02-26 02:37 UTC, mpinheir commented on app/busca/layout.tsx
@Zezola você mandou a mudança da página de Busca Layout junto com o PR para remover o menu da página principal do site. Remove esta modificação deste PR por favor. Obrigado.

2024-02-27 01:35 UTC, magnussolidus requested changes
Realize as alterações que o @mpinheir comentou.

2024-02-27 04:45 UTC, mpinheir commented
@Zezola pode fechar o PR?

2024-02-27 22:04 UTC, magnussolidus commented
Fechando o PR. Caso seja necessário, abra um novo PR com as alterações necessárias.

2024-02-27 22:04 UTC, closed without merging

2024-02-27 23:02 UTC, Zezola commented
Oi pessoal, desculpe a demora. Sem problemas, caso seja necessário abro outra PR com as alteraçoes necessarias